objects/Truck_load__c.object
<CustomObject>
    <label>Truck load</label>
    <nameField>
        <label>Truck load by which Person</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Truck loads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Material__c</fullName>
        <label>Material</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>cement</fullName>
                </value>
                <value>
                    <fullName>house hold goods</fullName>
                </value>
                <value>
                    <fullName>industrial equipments</fullName>
                </value>
                <value>
                    <fullName>metals</fullName>
                </value>
                <value>
                    <fullName>other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Schedule_Time__c</fullName>
        <label>Schedule Time</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>Material_Weight__c</fullName>
        <label>Material Weight</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

classes/Savetruckload.cls
public with sharing class Savetruckload {
  @auraEnabled
  public static Truck_load__c loaditem(string name,string material,Decimal materialweight,Time scheduletime)
  {

    Truck_load__c trload=new Truck_load__c();
    trload.Name=name;
    trload.Material__c=material;
    trload.Material_Weight__c=materialweight;
    trload.Schedule_Time__c=scheduletime;
    insert trload;
    return trload;

  }
}