objects/Truck__c.object
<CustomObject>
    <label>Truck</label>
    <nameField>
        <label>Truck Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trucks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Truck_booking__c.object
<CustomObject>
    <label>Truck booking</label>
    <nameField>
        <displayFormat>BKNO-{0000}</displayFormat>
        <label>Booking number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Truck bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Truck__c</fullName>
        <label>Truck</label>
        <referenceTo>Truck__c</referenceTo>
        <relationshipLabel>Truck bookings</relationshipLabel>
        <relationshipName>Truck_bookings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Truck bookings</relationshipLabel>
        <relationshipName>Truck_bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pincode__c</fullName>
        <label>Pincode</label>
        <precision>6</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

classes/savebookingdetails.cls
public with sharing class savebookingdetails {
    @AuraEnabled   
    public static void saverecords()
    {
    //     Truck_booking__c bookdetails=new Truck_booking__c();
    //     Id userId=UserInfo.getUserId();
    //     Account a=[select Id from Account where CreatedById=:userId];    
    //     bookdetails.Account__c=a;
    //     bookdetails.Truck__c='Ford Trucks 4142D';
    //   bookdetails.Pincode__c=36546;
    //   insert bookdetails;

     

    }
    public savebookingdetails() {

    }
}